# Generated by Django 3.2.18 on 2023-04-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='host',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='name',
        ),
        migrations.CreateModel(
            name='CampaignDetailsWithInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('postedDate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('brandName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.brand')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.hashtag')),
                ('influencerName', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.influencer')),
            ],
        ),
    ]
