# Generated by Django 3.2.18 on 2023-04-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230403_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('storyCost', models.IntegerField()),
                ('postCost', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='campaigns_done',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='influencers',
        ),
        migrations.AddField(
            model_name='brand',
            name='campaigns_count',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.campaign'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='brandmanager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='campaigns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.campaign'),
        ),
    ]
