# Generated by Django 3.2.18 on 2023-04-07 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230407_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='name',
        ),
        migrations.AlterField(
            model_name='filter',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hashtag'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.campaign'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager'),
        ),
    ]
