# Generated by Django 3.2.18 on 2023-04-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230407_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='campaign',
            new_name='campaign_hashtag',
        ),
        migrations.AddField(
            model_name='campaign',
            name='hashtag_campaign',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='max_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='max_child_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='max_children_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='max_followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='min_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='min_child_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='min_children_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='min_followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='parents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='campaigns_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filter',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hashtag'),
        ),
        migrations.CreateModel(
            name='SubBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subbrand_name', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brandmanager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
