# Generated by Django 3.2.18 on 2023-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='BrandReport',
        ),
    ]
