# Generated by Django 3.2.18 on 2023-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20230414_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='engagement_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
