# Generated by Django 3.2.18 on 2023-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_influencer_engagement_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='engagement_ratee',
            field=models.IntegerField(default=0),
        ),
    ]
