# Generated by Django 3.2.18 on 2023-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_influencer_engagement_ratee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='engagement_ratee',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
