# Generated by Django 3.2.18 on 2023-04-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20230419_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmanager',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerCampaignCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerFollowerCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerFollowingCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerPostCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerStoryCount',
        ),
        migrations.RemoveField(
            model_name='pragency',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='pragency',
            name='password',
        ),
    ]
