# Generated by Django 3.2.18 on 2023-04-23 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20230423_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcampaign',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
