# Generated by Django 3.2.18 on 2023-04-24 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_newcampaign_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcampaign',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='newcampaign',
            name='updated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
