# Generated by Django 3.2.18 on 2023-04-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20230427_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewInfluencer',
            new_name='Influencers',
        ),
    ]
