# Generated by Django 3.2.18 on 2023-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_rename_influencers_newinfluencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinfluencer',
            name='influencerAge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinfluencer',
            name='influencerChildExist',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='newinfluencer',
            name='influencerChildrenAge',
            field=models.CharField(blank=True, choices=[('toddler', 'toddler'), ('preschooler', 'preschooler'), ('elementary', 'elementary'), ('teen', 'teen'), ('adult', 'adult')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newinfluencer',
            name='influencerGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newinfluencer',
            name='influencerInfluencerPostCost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newinfluencer',
            name='influencerStoryCost',
            field=models.IntegerField(),
        ),
    ]
