# Generated by Django 3.2.18 on 2023-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20230430_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinfluencer',
            name='influencerFollowers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newinfluencer',
            name='influencerInfluencerPostCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newinfluencer',
            name='influencerStoryCost',
            field=models.IntegerField(default=0),
        ),
    ]
