# Generated by Django 3.2.18 on 2023-04-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20230430_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerAge',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerChildExist',
            new_name='childExist',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerChildrenAge',
            new_name='childrenAge',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerChildrenCount',
            new_name='childrenCount',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerInfluencerPostCost',
            new_name='ctorycost',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerFollowers',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencer_full_name',
            new_name='fullnname',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerGender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerInterests',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencerStoryCost',
            new_name='postcost',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='influencer_username',
            new_name='username',
        ),
    ]
