# Generated by Django 3.2.18 on 2023-04-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20230430_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='childExist',
            new_name='isparent',
        ),
    ]
