# Generated by Django 3.2.18 on 2023-05-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20230430_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinfluencer',
            name='isparent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=20),
        ),
    ]
