# Generated by Django 4.1.7 on 2023-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_admin_pragency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragency',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
