# Generated by Django 4.1.7 on 2023-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pragency_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='total_cost',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencers',
            field=models.ManyToManyField(blank=True, to='base.influencer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
