# Generated by Django 3.2.18 on 2023-04-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230403_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='filter',
            name='hashtag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='influencer_username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pragency',
            name='pragency_username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
