# Generated by Django 3.2.18 on 2023-04-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230407_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cost_per_influencer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hashtag', unique=True),
        ),
    ]
