# Generated by Django 3.2.18 on 2023-04-09 08:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_hashtag_total_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragency',
            name='confirm_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='pragency',
            name='password',
            field=models.CharField(default='', max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must contain at least 8 characters including at least one lowercase letter, one uppercase letter, one digit, and one special character', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+]).{8,}$')]),
        ),
        migrations.AddField(
            model_name='pragency',
            name='pragency_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pragency',
            name='pragency_username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
