# Generated by Django 3.2.18 on 2023-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20230409_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmanager',
            name='brandmanager_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pragency',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
