# Generated by Django 3.2.18 on 2023-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20230409_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
