# Generated by Django 3.2.18 on 2023-04-11 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_brandmanager_brandmanager_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('active_influencers', models.ManyToManyField(blank=True, to='base.Influencer')),
                ('campaign_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.campaign')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
