# Generated by Django 3.2.18 on 2023-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_influencer_engagement_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='engagement_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
