# Generated by Django 3.2.18 on 2023-04-19 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_engagement_ratee_influencer_engagement_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='campaign_hashtag',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='hashtag_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hashtag'),
        ),
    ]
