# Generated by Django 3.2.18 on 2023-04-19 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20230419_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='hashtag_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hashtag'),
        ),
    ]
