# Generated by Django 3.2.18 on 2023-04-23 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20230423_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcampaign',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='newcampaign',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='newcampaign',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
