# Generated by Django 3.2.18 on 2023-04-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20230423_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaign',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single')], default='DEFAULT', max_length=20),
        ),
    ]
