# Generated by Django 3.2.18 on 2023-04-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_influencers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Influencers',
            new_name='NewInfluencer',
        ),
    ]
