# Generated by Django 3.2.18 on 2023-04-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_rename_childexist_newinfluencer_isparent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='fullnname',
            new_name='fullname',
        ),
    ]
