# Generated by Django 3.2.18 on 2023-05-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_newinfluencer_isparent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='childrenAge',
            new_name='children_age',
        ),
        migrations.RenameField(
            model_name='newinfluencer',
            old_name='childrenCount',
            new_name='children_count',
        ),
    ]
