# Generated by Django 3.2.18 on 2023-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20230501_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinfluencer',
            name='isparent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
